"""Model-wide constants shared by all screens."""

from __future__ import annotations

SOLAR_CONSTANT = 1361.0
CO2_BASELINE_PPM = 280.0
REFERENCE_TEMP_C = 14.8
ALBEDO_REF = 0.30

DEFAULT_SEASONALITY_AMPLITUDE = 0.12
DEFAULT_ICE_TRANSITION_TEMP_C = -10.0
ICE_TRANSITION_WIDTH_C = 5.0

NATURAL_OUTGASSING_PPM_PER_YEAR = 0.9
DEFAULT_WEATHERING_STRENGTH = 0.55
DEFAULT_BIOSPHERE_UPTAKE_STRENGTH = 0.50
BIOSPHERE_OPT_TEMP_C = 15.0
BIOSPHERE_TEMP_WIDTH_C = 15.0

K_FLUX = 55.0
K_ALBEDO = 85.0
DEFAULT_K_CO2 = 5.35
WEATHERING_COEFF = 0.94 * DEFAULT_WEATHERING_STRENGTH * 0.50
WEATHERING_TEMP_SENS = 0.045
BIOSPHERE_COEFF = 0.94 * DEFAULT_BIOSPHERE_UPTAKE_STRENGTH * 0.50
EMISSIONS_TO_PPM_PER_YEAR = 1.0

SIM_YEARS_DEFAULT = 500
SIM_DT_YEARS_DEFAULT = 1.0
TEMPERATURE_RESPONSE_YEARS = 12.0
PREVIEW_HORIZON_YEARS = 100

HABITABILITY_LAT_BANDS = 181
HABITABILITY_SOFT_MARGIN_C = 1.6

TEMP_HOT_THRESHOLD_C = 32.0
TEMP_COLD_THRESHOLD_C = -5.0
CO2_DANGER_THRESHOLD_PPM = 1000.0
HABITABILITY_THRESHOLDS = (75, 50, 25)

DEFAULT_PLANET_RADIUS_KM = 6371.0
DEFAULT_SEED = 42

EMISSIONS_MODES = (
    "Constant",
    "Growing",
    "Carefree",
    "Stabilization",
    "Aggressive Mitigation",
)

HABITABILITY_PROFILES = {
    "Liquid Water": (0.0, 45.0),
    "Conservative Biosphere": (5.0, 32.0),
    "Broad Microbial Tolerance": (-10.0, 55.0),
}

SCENARIO_VERSION = "v2"

